### ISSUE TITLE
格式

### ISSUE THREAD

**Issue by crow-1412** [3000ye/dhuBachelor#1]
**分项应采用“(1)(2)(3)"，现有格式为"(i)(ii)(iii)"**
![image](https://github.com/3000ye/dhuBachelor/assets/141846839/09a8f3e0-8c98-45d0-9010-f734db64cf25)
![image](https://github.com/3000ye/dhuBachelor/assets/141846839/93aabe40-25ba-4c0a-944c-25f0c968acca)

**Comment by 3000ye** [comment]
已修复，下载使用最新版的 resume/xxx.sty 文件，然后替换就可以了。
